### ISSUE TITLE
Auto-create topojson files using OGR2OGR or other tools

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/piecewise#117]
Currently we ask the deployer to bring in Shapefiles and create a topojson file. If Piecewise could automatically create a topojson file from included .shp files, all the better. 

From dwins in PR #115 comments:
Definitely possible to do it on the server with Postgres or OGR2OGR. Both have some caveats though - Postgres's TopoJSON support requires kind of a lot of code to use and creates an auxiliary table (http://postgis.net/docs/manual-dev/AsTopoJSON.html) Note that the demo there hard-codes the transform so you may getting worse file size compared with a more full-featured implementation. OTOH OGR2OGR is likely to use a lot of memory and might have trouble with larger datasets on smaller VMs.

**Comment by BobBallance** [comment]
It would be straightforward to add an 'export' option to the I3Connectivity Explorer --- they could set up the notebook with the areas that they want and then get the underlying area as a GeoJSON file. Could add support for the bounding block as well... We'd still need to look at TopoJSON, though, but I have almost all of the useful files on the server already.
