### ISSUE TITLE
Match the map tile sets, between the base map and the current location map

### ISSUE THREAD

**Issue by georgiamoon** [opentechinstitute/piecewise#12]

**Comment by georgiamoon** [comment]
or as @gembarrett said - don't use a map for the "your location" piece -- put text.

**Comment by nkinkade** [comment]
True.  I only placed the map image there as part of the crude prototype I tossed together to show how it could work....  it certainly never was meant to be there permanently.  By all means, it can be dropped for something more useful and appropriate!

**Comment by nkinkade** [comment]
Closing this because we aren't going to display the current location in a separate map image, that I know of.  If this isn't true, then reopen this issue, if it's still an issue.
