### ISSUE TITLE
Allow for swapping between district and Census polygon layers

### ISSUE THREAD

**Issue by georgiamoon** [opentechinstitute/piecewise#13]
(At least) Two options for polygon layers:
- districts,
- census block, 
- any others

**Comment by nkinkade** [comment]
This is a nice feature, generally, but are you sure that Seattle actually wants this?  My understanding is that they wanted to stay away from aggregating by council districts because it was potentially too politically charged.

**Comment by critzo** [comment]
In our last conversation with them, they would like the ability to toggle between census block groups and council districts. 

For this issue, let's confirm that piecewise is aggregating both and providing the data. I'm going to put the UI components of this issue to bq2geojson.

**Comment by nkinkade** [comment]
We should verify this with Bruce before we work on this. I distinctly recall Bruce saying that council districts were too politically charged for them to use, and that was one of the reasons why census block groups were preferred.  This last call did not include Bruce, and I'm not sure that Neil had/has all the information Bruce is working with.

**Comment by critzo** [comment]
I sent a note to the Seattle folks asking to confirm their needs on this
feature.

**Comment by critzo** [comment]
@nkinkade How's this going?

**Comment by critzo** [comment]
This should actually have been logged in bq2geojson

**Comment by nkinkade** [comment]
Done.  m-lab/bq2geojson@a72c1d4
