### ISSUE TITLE
Remove map from background of speed.digitalinclusion.org instance

### ISSUE THREAD

**Issue by laiyi-ohlsen** [opentechinstitute/piecewise#157]
Until we get the map vis up and running its a bit confusing to have the map on the survey page. Let's make it a fixed white background, maybe without the survey/speed test being an overlay (open to whatever is easiest)

**Comment by critzo** [comment]
In this commit I've disabled interactivity of the map so it shows up but just looks like a background.

https://github.com/m-lab/piecewise/commit/089b1a3a15a9c6bd272521bcb46510555b12ed94

Does that work @laiyi-ohlsen ?

**Comment by critzo** [comment]
@laiyi-ohlsen per our chat, I've mocked up additional changes that can be previewed here:
https://35.208.161.188/
