### ISSUE TITLE
confirm that updating piecewise data via a cron job works

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/piecewise#16]
piecewise was originally designed to pull data from a specified time window. Nathan has added the function to piecewise.aggregate to truncate the database table when it is rerun, but we need to confirm that updating via cron will work properly to bring in new data.

[ ] confirm methods for updating the data selection via cron script works 
[ ] draft instructions on how to update data on a regular basis for an instance of piecewise

**Comment by nkinkade** [comment]
Done.  I added the following cron job to root's crontab for a few days on our live demo server and it seems to work just fine:

21 1 \* \* \* cd /opt/piecewise && python -m piecewise.ingest
