### ISSUE TITLE
debug and fix submissions endpoint flapping, regular 500 errors

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/piecewise#162]
We've had many reports about the standalone prod site. @jheretic @rudietuesdays could you please take a look today?
* include the submissions api endpoint not being available or going up and down 
* regular "something went wrong 500" errors

![image](https://user-images.githubusercontent.com/4633345/77533336-14f03a80-6e6d-11ea-8292-ab0aa34dbfda.png)
![Screenshot from 2020-03-23 16-24-27](https://user-images.githubusercontent.com/4633345/77533437-3cdf9e00-6e6d-11ea-8d97-dfc26647452d.png)
![Screenshot from 2020-03-23 16-24-49](https://user-images.githubusercontent.com/4633345/77533438-3d783480-6e6d-11ea-810f-88a94cae91ab.png)

**Comment by critzo** [comment]
I just restarted the PW containers on production. Before doing so I did a database submissions table export and the exported contents include this psql error:
`psql: error: could not connect to server: FATAL:  sorry, too many clients already`
(relates to 500 error)

**Comment by critzo** [comment]
After service restart, the 500 error is gone, but we have the Bad Gateway error for the submissions API endpoint.

**Comment by critzo** [comment]
#159 fixed the geo-location issues resulting in the appearance of "stalled" tests, or users who want to run a test but not share location data. However, the submissions API endpoint is still down and a 500 error is presented in the browser console output.

**Comment by laiyi-ohlsen** [comment]
Resolved by @rudietuesdays!
