### ISSUE TITLE
users receive a "something went wrong: 500" dialog box

### ISSUE THREAD

**Issue by laiyi-ohlsen** [opentechinstitute/piecewise#163]
From a user on the NDIA listserv: 
"I've been getting this message periodically from that page "Something went wrong: 500" in a dialog box. I can close it and then access the site and the test just fine. Happening across multiple browsers and devices."

I also reproduced but was silly and forgot to take a screenshot! Went away upon refreshing. Will post if it happens again

**Comment by critzo** [comment]
Additional details in #162

**Comment by laiyi-ohlsen** [comment]
Should be resolved by @rudietuesdays
