### ISSUE TITLE
periodic 500 error presented, requiring a docker-compose restart

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/piecewise#168]
Periodically we have had reports of people receiving 500 errors when loading a Piecewise site. The solution has been to restart the container services using `docker-compose restart`, so perhaps we need a cron task or something to periodically do this automatically. Further, it would be nice to trace down why it's happening and solve the root cause. @jheretic where does the application send it's log messages?

**Comment by jheretic** [comment]
While we're troubleshooting and working on a replacement, the connection limit has been tripled.

**Comment by jheretic** [comment]
Also just to note, logs for the back end can be found with `docker logs piecewise-backend`
