### ISSUE TITLE
confirm that new installations of piecewise properly ingest data and create aggregate stats

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/piecewise#17]
Chris encountered an issue with his test installation, where the aggregate statistics table had not been populated in postgres. For a brand new vagrant VM instance, this should not be the case. There was an error in /var/log/piecewise/wsgi.log:

ProgrammingError: (psycopg2.ProgrammingError) relation "block_statistics" does not exist
LINE 2: FROM block_statistics, seattle_blkgrpce10

**Comment by nkinkade** [comment]
I'll need access to that VM to be able to troubleshoot this any further myself.  I haven't seen that error before, and in the past week I've completely redeployed piecewise from scratch both a local VM and a remote server with no issues at all.  Other logs to check would be /var/log/daemon.log to look for uwsgi issues on startup, and /var/log/piecewise/collector.log, and possibly /var/log/nginx/error.log to be sure it's not nginx complaining about something.
