### ISSUE TITLE
Verify that ISP aggregations are happening correctly

### ISSUE THREAD

**Issue by nkinkade** [opentechinstitute/piecewise#18]
ISP aggregations are happening, but lots of aggregations lack any ISP assignment, which makes me think that either the code is wrong or the the maxmind database we have is not complete for Seattle.

**Comment by critzo** [comment]
@nkinkade Can we check with Collin/Michael about confirming whether we have the most up to date information from Maxmind?

**Comment by critzo** [comment]
Also, per the City's [requirement 3.2](https://github.com/openseattle/seanetmap/wiki/Requirements-from-the-City-of-Seattle%2C-Annotated#cityreq32), does piecewise currently provide or can it be modified to provide:
- aggregation of metrics by provider, by shape area
- aggregation of metrics by time of day, both overall (all ISPs and split by provider)

It may be that we need to use the scripts within telescope to generate the last bit.

**Comment by critzo** [comment]
@georgiamoon 
In conversations with cdwinslow, we've identified that the reason only some ISPs are being aggregated has to do with incomplete regexes on the ISP names in Maxmind. Need to update regexes in : https://github.com/opentechinstitute/piecewise/blob/master/seattle_example/piecewise_config.json#L32

**Comment by critzo** [comment]
This issue is resolved with recent updates to master from the add-isp-regexes branch.
