### ISSUE TITLE
Confirm median is being correctly calculated 

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/piecewise#2]

**Comment by nkinkade** [comment]
I believe these commits fix the median issue:

dc9a3c3c703f66270a683ef7a6faa00b771aca59
1b001b09e2d8fc1b9872df896e7f3e6c662d1119
8f82c1fa862e091ce52466224769f93875c84c3d

And this commit in bq2geojson fixed a  bug where the start and end dates for any given month were slightly off, causing Piecewise to return incorrect data and median values were duplicated:

m-lab/bq2geojson@f0af66040a1152a2ad73ea90d5aeeb711176b6ec

**Comment by critzo** [comment]
@nkinkade have these commits been merged into master? if not, let's issue a pull request and merge them in.

**Comment by nkinkade** [comment]
Yes, all those commits are in master.  Since I've been the only person working on piecewise, I've been working directly on master.
