### ISSUE TITLE
Issue re: data in admin panel

### ISSUE THREAD

**Issue by owenwhenry** [opentechinstitute/piecewise#201]
Hey folks,

we're working on setting up an instance of this in Baltimore! We've got the app up and running in docker but ran into an issue with the data in the back end - whenever it tries to pull it down from the DB using the /submissions route it throws the following error:

{"statusCode":400,"error":"Bad Request","message":"Failed to parse query: SyntaxError: Unexpected token o in JSON at position 1"}

We don't have anything in the user table so entirely possible it's a permissions issue, but I've got no idea what kind of values I need to throw in there. Any suggestions for what I should look at to fix it?

**Comment by critzo** [comment]
Hi @owenwhenry, that's awesome!

I just made this addition to README.md to clarify, but before building the containers you should at least supply a value for `PIECEWISE_ADMIN_PASSWORD` in your .env file or in an environment variable available to your container. Then once built and deployed, you can login using the `/login` route to access submissions and configure the survey and other options.

The `/submissions` route provided by the API depends on a browser authenticated session at the moment, so once you are logged in, it should return JSON results. We'd like to add other methods of using the API like an API key in the future.

You can also define a "viewer" users in the .env or environment variable. I think for a standalone deployment of Piecewise in Docker, this is the way to define users. @jheretic is that correct? 

If you're looking for other features like user management and multiple Piecewise instance management, we developed [piecewise-saas](https://github.com/m-lab/piecewise-saas) that provides those features.

A couple other notes- once logged in, your admin account should have access to build the survey and begin accepting results. These are viewable/downloadable in the Data page. The map page is intended to retrieve base tiles from M-Lab showing aggregate results in specific geographies, as well as FCC data and census statistics for the same geography. I'm not sure of this feature's status. The map will also show your collected test results.

I hope this helps. Please let us know if you run into other issues or have additional questions.

**Comment by owenwhenry** [comment]
Hey,

I've got it building with the admin password and handling the login just fine. The only problem is with actually viewing data on the settings tab - it gives me the error I mentioned above. I wasn't able to figure out what the JSON error it was referring to was, but based on what you wrote above I wonder if it's talking about the session. 

I also noticed you added a couple of instructions for running the db:migrate and db:seed commands in the Docker instructions since I first started mucking with it a couple months ago (or maybe I didn't see them). I can tear down what I've done (no data's been actually collected, so no harm no foul) and set it up with those commands if you think failing to run either would prevent me from seeing data, but when I glanced at those files I didn't see a reference to the users table.

**Comment by critzo** [comment]
Ok. Sorry if I misunderstood. The changes to the `db:seed` and `db:migrate` were needed to exec the command in the specific container. We'd not updated those lines in the documentation. If you're tearing down/rebuilding a fresh container you might try using those updated commands. Migrate sets up the database I think, and seed adds your user(s) and some seed data. I would recommend running those.

Re: the error, I'll re-test and see if I can reproduce.

**Comment by jheretic** [comment]
@owenwhenry You'll need to run the `db:migrations` and `db:seeds` commands for it work. The `users` table is only used when the instance is hooked up to piecewise-saas, so I wouldn't expect to see it populated.

**Comment by critzo** [comment]
@owenwhenry Did running the `db:migrations` and `db:seeds` commands resolve this issue for you?

**Comment by owenwhenry** [comment]
Yep, there were some other tweaks had to make but that did indeed do it for
not being able to see the data. Thank you!

**Comment by critzo** [comment]
Awesome. We'd love to see the site once it's live if you can share. Thanks!
