### ISSUE TITLE
Make sure we always have the most up-to-date maxmind database

### ISSUE THREAD

**Issue by nkinkade** [opentechinstitute/piecewise#21]
I _believe_ the current database is being pulled in through a git clone of telescope, but Collin confirms that the database in the telescope repo is at least a year old.

**Comment by critzo** [comment]
@nkinkade Here are some resources on the Maxmind database, in the case we need to use a different means of grabbing it instead of Telescope:
- http://dev.maxmind.com/geoip/geoip2/geolite2/
- http://dev.maxmind.com/geoip/legacy/geolite/
- http://geoip2.readthedocs.org/en/latest/

@collina Telescope uses geolite2, right?

**Comment by critzo** [comment]
Looks like the file maxmind.py is importing the group database that telescope brings in. We could either update telescope to load the newest database from maxmind, or set up a part of piecewise  to curl or wget the latest database

**Comment by nkinkade** [comment]
It is using the MaxMind CSV from telescope, but the import into the maxmind table in the database happens in setup.sql at the time of deployment.  I think easier than relying on whoever happens to be maintaining telescope to update the CSV is to do as you say, and that is to simply fetch the latest database at the time of deployment.   It will then be up to the maintainer of any given deployment to update the table on their own once in a while... it could be easily scripted.

**Comment by nkinkade** [comment]
Done @d2ad1d9.  Closing.

**Comment by critzo** [comment]
@nkinkade would that script fetch again via telescope or pull the database from maxmind? @collina let's add this to the feature set of telescope if we can. @nkinkade we'll need this update to happen for Seattle, as well as for an upcoming deployment of piecewise that @georgiamoon has discussed, so I'm reopening this issue. If you have ideas on a script to update the local piecewise instance post deployment it would vet great to have that done.

**Comment by critzo** [comment]
OK. Sorry, @nkinkade. Just read your code commit. I'm assuming you pulled in the latest database as well as updating the deploy code?

**Comment by collina** [comment]
@nkinkade and @critzo, I think its unlikely that telescope's repo will be updated continually to reflect the latest Maxmind, and piecewise's need for the most current data is more critical. Telescope probably even cares more about archival Maxmind copies than the absolute newest. I support @nkinkade's approach.

**Comment by nkinkade** [comment]
Yeah.  This was why I made @d2ad1d9 earlier today.  And @b251c84 is an example of a simple script for updating the maxmind table in the database with the most current data at some point in the future.  I'll update our example deployment and will email the Seattle people about updating their deployment.

**Comment by critzo** [comment]
@nkinkade @collina Thanks for weighing in on this guys. I think for piecewise, the script makes total sense and can easily be added to a crontab on a monthly basis as Maxmind releases new data. It also makes me think about how we do longitudinal tracking of IP-->ISP info. Maybe we'll discuss or approach that in the "replace PDE" conversation.
