### ISSUE TITLE
add a collector endpoint to provide a data dump for Seattle

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/piecewise#25]
We need a JSON endpoint for Seattle to consume data into data.seattle.gov that includes the following data as reported by NDT:
- test date/time, 
- ISP (as reported by Maxmind), 
- download speed, 
- upload speed, 
- round trip time, 
- and location (census block); 

as well as the following fields reported by users submitting the post-NDT test form: 
- type of location where test was run (residence, workplace, business, etc.), 
- ~~ISP (as reported by user),~~ connection type (cable, DSL, fiber, etc.), 
- advertised download speed, 
- advertised upload speed, 
- and monthly cost of service.

**Comment by critzo** [comment]
@nkinkade I've started work on this in the branch issue25 -- If we can work on this together that would be great.

**Comment by nkinkade** [comment]
@critzo ... sure, just let me know when/where you want me to jump in.  I don't want to just randomly start working on it to avoid duplicating effort.  Are you finished for now and just want me to pick up where you've left off?

**Comment by critzo** [comment]
@nkinkade you can go for it. I'm sure you'll make quicker work of it comparatively. Thanks.

**Comment by nkinkade** [comment]
This was done quite a while ago. partly through commit @7e2d409.  Closing.
