### ISSUE TITLE
Confirm aggregate stats for map utilize geoloc data in extra_data table

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/piecewise#3]

**Comment by nkinkade** [comment]
The code says that this should be the case:

https://github.com/opentechinstitute/piecewise/blob/master/piecewise/piecewise/aggregate.py#L265

The coalesce() function will return the first non-NULL value in the list, and the first one listed is extra_data.location... if that doesn't have a value then it falls back to results.location.
