### ISSUE TITLE
Determine how to correlate aggregate statics by ISP

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/piecewise#4]

**Comment by nkinkade** [comment]
I verified that this is at least nominally being done.  The isp column in the block_statistics table is getting populated some of the time with ISP names, but less of the time than I would expect.  My initial though is that either Piecewise code isn't correlating ISPs correctly based on the client IP, or that the maxmind table is somehow lacking or incorrect.  As far as obtaining the aggregations  based on ISP, one can simply add the query parameter &b.isp_bins when querying Piecewise via the /stats/q/ endpoint.  Closing this ticket, and will open another related to verifying that ISP mappings, maxmind and Piecewise code are working as well as they should be.
