### ISSUE TITLE
add test_id to results table in initial provisioning setup

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/piecewise#46]
The field test_id in the results table does not get created by default in a new Piecewise instance. In an initial clone of piecewise master branch, 'vagrant up' was run to provision the VM. When running the initial piecewise.ingest routine, however, after Big Query ingestion, the adding of results records fails because the column test_id doesn't exist.

**Comment by nkinkade** [comment]
I'm pretty sure that commit @7bdc215 should have served to add the field test_id to the deployment.  I believe the problem we are hitting was introduced in commit @cf2f767e, where if "piecewise_env" is set to "dev", then Ansible loads an example results tables, probably to avoid the lengthy part of pulling data from BigQuery.  However, that sample database doesn't include the "test_id" (created before field was added).  Two things should probably happen: 1) an example results table with all the fields should be added to the seattle_example directory 2) The Vagrantfile should be modified to set "piecewise_env" to something other than "dev" by default.  I'll do both of these things.

**Comment by nkinkade** [comment]
I think this is fixed with commits @a46083d to @b0ae80a ... test with "dev" environment and field showed up properly.  But the Vagrantfile now defaults to "live", so that should work as normal when ingest is run.
