### ISSUE TITLE
UI: Time slider: clicking on month name labels needs to propagate event

### ISSUE THREAD

**Issue by JohnTigue** [opentechinstitute/piecewise#48]
Repro:
- Load the map into a browser
- Click on a couple of month name labels in the time slider

Expected:
- Map redrawn to new month
- (If instead of clicking on the month name label, rather one clicks on the white box with blue border, then things happen as expected)

Actual:
- slider updates to new month but map does not

So the click event needs to be propagated from the slider to the map when month name labels are clicked on.

**Comment by critzo** [comment]
Flag to review this issue post-seattle launch and in code refactoring.
