### ISSUE TITLE
browser check "your approximate location"

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/piecewise#6]
The Google map that shows the users' HTML5 geolocation works in Chrome but not in Iceweasel/Firefox.  Need to check and modify code to show the map under "your approximate location" or determine whether to disable this feature in the right sidebar.

**Comment by nkinkade** [comment]
This isn't a bug in our code:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=726230

**Comment by nkinkade** [comment]
This may be limited to Iceweasel only, but since this isn't an issue with our code or anything in this repo, closing.
